### ISSUE TITLE
ara::exec::DeterministicClient::WaitForActivation()

### ISSUE THREAD

**Issue by luckeyhy** [langroodi/Adaptive-AUTOSAR#22]
Is the content of the function body in the title incomplete?Its function return value should contain all members of the enumeration class.
However, the function can only return a fixed local variable: kRun.

**Comment by langroodi** [comment]
Yes, it is incomplete! After the first implementation (which returns only the `kRun`), returning the `kServiceDiscovery` was also part of the scope.
But when the project grew, determining the service discovery state became more complex than expected which required a synchronization between SM and DM via ara::com.
 So, at the end, the scope stayed the same as the current implementation. Please refer to the following commit:
https://github.com/langroodi/Adaptive-AUTOSAR/commit/6d9b047be3b411168389894274fda4752c49d9e5#diff-8bc72e8ee3e95b6132a858a8c5a2e78ace22b4c47c54f0752f409f8b26171fae
