### ISSUE TITLE
error log occur

### ISSUE THREAD

**Issue by magic-tab-01** [langroodi/Adaptive-AUTOSAR#29]
enviroment：
linux：

Linux magic 5.15.0-86-generic 
96~20.04.1-Ubuntu SMP Thu Sep 21 13:23:37 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux

cmake：
 3.16.3
gcc version：
gcc version 9.4.0 (Ubuntu 9.4.0-1ubuntu1~20.04.2) 
branch：
origin/master

produce：
after i run “./build/bin/adaptive_autosar ./configuration/execution_manifest.arxml ./configuration/extended_vehicle_manifest.arxml ./configuration/diagnostic_manager_manifest.arxml ./configuration/health_monitoring_manifest.arxml” igot log as below, could you kindly help?

Tue Oct 24 20:34:53 2023
 PlatformHeathManagement Context ID:Lifetime;Context Description:Application lifetime logs;Log Level:Info;Plafrom health management has been initialized.
Tue Oct 24 20:34:53 2023
 ExtendedVehicle Context ID:Lifetime;Context Description:Application lifetime logs;Log Level:Info;Extended Vehicle AA has been initialized.
Tue Oct 24 20:34:53 2023
 DiagnosticManager Context ID:Lifetime;Context Description:Application lifetime logs;Log Level:Info;TelematicControlModuleMonitor is offered.
Tue Oct 24 20:34:53 2023
 DiagnosticManager Context ID:Lifetime;Context Description:Application lifetime logs;Log Level:Info;Diagnostic Manager has been initialized.
Tue Oct 24 20:34:53 2023
 StateManagement Context ID:Lifetime;Context Description:Application lifetime logs;Log Level:Info;EM initial machine state transition is fetched successfully.
Tue Oct 24 20:34:53 2023
 StateManagement Context ID:Lifetime;Context Description:Application lifetime logs;Log Level:Info;EM is transited to the start-up state successfully.
Tue Oct 24 20:34:53 2023
 StateManagement Context ID:Lifetime;Context Description:Application lifetime logs;Log Level:Info;Execution state is reported successfully.
Tue Oct 24 20:34:59 2023
 DiagnosticManager Context ID:Lifetime;Context Description:Application lifetime logs;Log Level:Error;TelematicControlModuleEvent is failed with DTC 49560
Tue Oct 24 20:35:03 2023
 LogRecoveryAction Context ID:RecoveryAction;Context Description:Recovery action logs;Log Level:Error;Alive supervision is expired on MachineFG
Tue Oct 24 20:35:05 2023
 ExtendedVehicle Context ID:Lifetime;Context Description:Application lifetime logs;Log Level:Error;Setting the VIN failed due to unexpected RESTful response format.

**Comment by langroodi** [comment]
I've already answered that how to debug this specific issue [here](https://github.com/langroodi/Adaptive-AUTOSAR/discussions/27). Please continue the discussion at the topic. This issue will be closed for now.
