### ISSUE TITLE
This repository is base on which version of AP?

### ISSUE THREAD

**Issue by pzibang** [langroodi/Adaptive-AUTOSAR#3]
Hi, I want to know this repository is base on which version of AP?

**Comment by langroodi** [comment]
Hi!

ara::core and ara::em are based on R19-11 (but also not fully compatible with the standard) and ara::com, ara::diag, ara::sm, and ara::log are based on R20-11.
The goal is to stick with the latest standard revision as much as possible (if I have time for the upgrade to the newer version).

**Comment by pzibang** [comment]
Thank you for your selflessness and I'll keep an eye on your repository.
